auth-lb:
  scale: 1
  load_balancer_config:
    name: auth-lb config
  default_cert: test.techtraits.com_self_signed
mysql-master:
  scale: 1
auth-service:
  scale: 1
  health_check:
    port: 9000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /health HTTP/1.0
    healthy_threshold: 2 
    response_timeout: 2000
